[package]
name = "rust-Qt-OSM"
version = "0.1.0"
edition = "2024"

[dependencies]

cxx = "1.0.188"
cxx-qt = "0.7.3"
cxx-qt-lib = {version = "0.7.3", features = ["full"]}

[build-dependencies]
cxx-qt-build = "0.7.3"
