[package]
name = "rust-Qt-OSM"
version = "0.1.0"
edition = "2021"

[dependencies]

cxx = "1.0.95"
cxx-qt = "0.7"
cxx-qt-lib = {version = "0.7", features = ["full"]}

[build-dependencies]
cxx-qt-build = "0.7"
